# Generated by Django 6.0.3 on 2026-03-24 20:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('channel', models.CharField(choices=[('organic', 'Organic'), ('paid', 'Paid'), ('referral', 'Referral'), ('newsletter', 'Newsletter'), ('direct', 'Direct')], db_index=True, default='direct', max_length=20)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], db_index=True, default='desktop', max_length=20)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('is_returning', models.BooleanField(default=False)),
                ('is_conversion', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
